apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe --file docker-compose.yml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe --file docker-compose.yml convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.service: todo-app
    spec:
      initContainers:
        - name: init-todo-db
          image: todo-react-flask-pgsql-todo-app:latest
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c", "flask db upgrade"]
          envFrom:
            - configMapRef:
                name: todo-app-config
      containers:
        - name: todo-app
          image: todo-react-flask-pgsql-todo-app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: todo-app-config
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /var/log/todo
              name: todo-app-logs
      restartPolicy: Always
      volumes:
        - name: todo-app-logs
          persistentVolumeClaim:
            claimName: todo-app-logs
