apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe --file docker-compose.yml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: todo-ui
  name: todo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe --file docker-compose.yml convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.service: todo-ui
    spec:
      containers:
        - image: todo-react-flask-pgsql-todo-ui:latest
          imagePullPolicy: IfNotPresent
          name: todo-ui
          ports:
              - containerPort: 80
                protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
