apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe --file docker-compose.yml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: todo-db
  name: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe --file docker-compose.yml convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.service: todo-db
    spec:
      containers:
        - name: todo-db
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: todo-app-config
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: todo-db-data
      restartPolicy: Always
      volumes:
        - name: todo-db-data
          persistentVolumeClaim:
            claimName: todo-db-data
